server:
  port: 8091
spring:
  application:
    name: account
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eamon_shopping?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.217.129:8848
    # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
    alibaba:
      seata:
        enabled: true
        application-id: ${spring.application.name}
        #tx-service-group: account-service-fescar-service-group
        tx-service-group: my_test_tx_group
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: eamon.springcloud.account.entity